name: get pull request info for Dingding

on:
  push:
  pull_request:

jobs:
  spring-boot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
      
    # 此处省略具体的业务代码    
   
    # 获取PR信息并将其添加到环境变量
    - name: set PR_INFO 
      run: |
        echo PR_USER=$(jq --raw-output .compare "$GITHUB_EVENT_PATH") >> $GITHUB_ENV
        cat $GITHUB_EVENT_PATH
        echo "$(jq '.comment.id' $GITHUB_EVENT_PATH)"
        export COMPARE=$(jq '.compare' $GITHUB_EVENT_PATH|sed 's/\"//g' | sed 's/.*\/\([^\/]*\)$/\1/')
        export AFTER=$(jq '.after' $GITHUB_EVENT_PATH|sed 's/\"//g')
        export BEFORE=$(jq '.before' $GITHUB_EVENT_PATH|sed 's/\"//g')
        if [[ -n ${{DIFF_PATH}} ]]
        then
          echo "did't set DIFF_PATH "
          export PATH="."
        else
          export PATH=${{DIFF_PATH}}
        git diff $COMPARE $PATH > temp
        echo 'DIFFLOG<<EOF' >> $GITHUB_ENV
        cat temp
        cat temp >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        
    # 打印环境变量
    - name: print env
      run: printenv
     
    # 发送钉钉消息
    - name: build success
      if: ${{ success() && env.DIFFLOG != ''}}
      uses: fifsky/dingtalk-action@master
      with:
        url: https://oapi.dingtalk.com/robot/send?access_token=${{secrets.DIFF_DINGDING_TOKEN}}
        type: text
        content: |
          💯👨‍💻 Success ${{ env.PR_USER }}
          
          ${{ env.DIFFLOG }}
    - name: maven build failure
      if: ${{ failure() }}
      uses: fifsky/dingtalk-action@master
      with:
        url: https://oapi.dingtalk.com/robot/send?access_token=${{secrets.DIFF_DINGDING_TOKEN}}
        type: markdown
        content: |
          # 💤🤷‍♀️ failure 🙅‍♂️💣
          > Maven Build of fail
          ${{ env.PR_USER }}
