name: get pull request info for Dingding

on:
  push:

jobs:
  spring-boot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
      
    # 此处省略具体的业务代码    
   
    # 获取PR信息并将其添加到环境变量
    - name: set PR_INFO 
      run: |
        echo COMPARE_URL=$(jq --raw-output .compare "$GITHUB_EVENT_PATH") >> $GITHUB_ENV
        export COMPARE=$(jq '.compare' $GITHUB_EVENT_PATH|sed 's/\"//g' | sed 's/.*\/\([^\/]*\)$/\1/')
        git diff $COMPARE README.md > temp
        echo 'DIFFLOG<<EOF' >> $GITHUB_ENV
        cat temp >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        
    # 打印环境变量
    - name: print env
      run: printenv
     
    # 发送钉钉消息
    - name: build success
      if: ${{ success() && env.DIFFLOG != ''}}
      uses: fifsky/dingtalk-action@master
      with:
        url: https://oapi.dingtalk.com/robot/send?access_token=${{secrets.DIFF_DINGDING_TOKEN}}
        type: text
        content: |
          💯👨‍💻 Success ${{ env.COMPARE_URL }}
          
          ${{ env.DIFFLOG }}
    - name: maven build failure
      if: ${{ failure() }}
      uses: fifsky/dingtalk-action@master
      with:
        url: https://oapi.dingtalk.com/robot/send?access_token=${{secrets.DIFF_DINGDING_TOKEN}}
        type: markdown
        content: |
          # 💤🤷‍♀️ failure 🙅‍♂️💣
          > Maven Build of fail
          ${{ env.COMPARE_URL }}
